### ISSUE TITLE
2.x Plan

### ISSUE THREAD

**Issue by sainthkh** [recharts/recharts#1910]
## Creating 1.x branch.

As we're going to migrate recharts to TypeScript, it'll be hard for us to maintain 2 versions at the same time. So, I guess we need to feature freeze 1.x version now and change them only when there is a severe bug like crashes or security problem. 

- [x] Create 1.x branch from 1.8.3 commit. When something happens on 1.x, we go back to this branch and fix them and release newer 1.x version.

## 2.0 Goals

In 2.0, we'll migrate 'src/' codes to TypeScript and support React 16. 

### Preparation -> #1911
- [x] Add `UNSAFE_` prefix back. I explained why we need them on #1905. 
- [x] Setup TypeScript with webpack.

### Main Migration.

Things to do:
* Get rid of propTypes. If we want to use propTypes, we might need to use [this plugin](https://www.npmjs.com/package/babel-plugin-typescript-to-proptypes).
* Define types. 
* As for 2.0.0, our goal is to define types, not refactoring. 

#### Phase 1 -> #1918
- [x] shape 
- [x] container
- [x] components. 

#### Phase 2
- [x] polar -> #1919
- [x] cartesian -> #1927
- [x] numberAxis -> #1927

#### Phase 3
- [x] util -> #1921
- [x] charts
- [x] Remove as many `any`s as possible. 

### Release
- [x] Commit 2.0.0 and publish it. 

## 2.1 and Later

* Migrate Chai tests to Jest.
* Introduce Storybook. 
* Maybe CI and eslint.
* Refactor codes that don't follow React convention (e.g. `render() { return null; }`)

**Comment by sainthkh** [comment]
As I don't have right to create 1.x branch on this repo. @xile611, please do this for us.

**Comment by dimitropoulos** [comment]
@sainthkh if you are interested in a very strict lint config that supports typescript natively, I have had good success with https://www.npmjs.com/package/eslint-config-intense

**Comment by sainthkh** [comment]
@dimitropoulos We'll check it out after 2.0 is done. I've added it to the list of 2.1 and later.

**Comment by matthewkwong2** [comment]
One important note:
Currently, it is unintuitive to create a wrapper component.
e.g. If I would like to create a styled, reusable `Line`, it is quite inconvenient to do the following:
```jsx
const CutomLine = () => (
    <Line
        {...someCustomizedProps}
    />
);
```

**Comment by avindra** [comment]
@matthewkwong2 That is common, though not sure about scalable. The React team has explicitly called out "prop-spreading" as an antipattern on numerous occasions. Here is one such reference:

https://reasonml.github.io/reason-react/docs/en/props-spread

> Props spreading is a big source of unpredictability and performance regression (think shouldComponentUpdate).

**Comment by avindra** [comment]
Been using the beta now for a few days... feels a bit faster. All the warnings about deprecated methods are gone in unit tests. Nice work!

**Comment by kLabz** [comment]
> [x] Remove as many `any`s as possible.

Is it considered done? I'm writing a [Haxe](https://haxe.org) wrapper for this library which consist mostly in strict typings for all components, and there are still **a lot** of `any` / `Function` out there, even for things that seem easy to type or have already been typed elsewhere on the project.

If the focus of 2.0 is to type everything, imo more can be done before releasing. If that's what you want too, I can help since while I do not know the internals well, I am working with types for this library. Help in the form of CI (I know it is there, but I don't know how far it goes) and/or example typescript projects that would need to keep compiling fine would allow me to propose these changes without breaking things.

**Comment by sorenhoyer** [comment]
Any plans of supporting React 17?

**Comment by oneillsp96** [comment]
Are there actually breaking changes in V2 or just a refactor to use typescript?
Can anyone comment on how stable the current v2 beta version seems?
Any idea when a stable V 2.x will be ready? 
Do you need help?

**Comment by rohit-gohri** [comment]
The v2 beta doesn't export any individual types. I had better support with v1 and the `@types/recharts` package. For eg.:

A Pie Chart with custom labels in v1:

```ts
import { ContentRenderer, PieLabelRenderProps, PieChart, Pie, Cell, Tooltip } from 'recharts';

const CustomLabel: ContentRendered<PieLabelRenderProps> = ({
  percent, name, id,
}) => `${truncate(name, { length: 9 })} (${id}) ${(percent * 100).toFixed(0)}%`;

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#90C49F', '#FFDB28'];

export default function PieComponent({data, key}) => {
	return (
        <PieChart>
          <Pie
            data={data}
            dataKey={key}
            nameKey="name"
            label={CustomLabel}
            cx="50%"
            cy="50%"
            outerRadius={80}
            fill="#8884d8"
          >
            {
              data.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)
            }
          </Pie>
          <Tooltip />
        </PieChart>
	);
}

```

When I tried this in v2 beta I couldn't add types to the `CustomLabel` component as the `PieLabel` type wasn't exported and even if it was it had `props: any` so it wasn't of  much use. Here:

https://github.com/recharts/recharts/blob/41f363a3ec2a5d16477e4c96fe9e2153ede6be84/src/polar/Pie.tsx#L56

This problem of non-exported types is almost everywhere. 

@xile611 @sainthkh Maybe a feedback issue could be opened for the beta?

**Comment by mkaraula** [comment]
Stmbled over a similiar Issue as @rohit-gohri  when using `YAxis` with a `label`. A label shows up but something is odd with the typing because Typescript basically tells me that there is no prop `label`

**Comment by nvh95** [comment]
> **2.1 and Later**
> Migrate Chai tests to Jest.

@sainthkh I just want to ask about the progress on migrating from Chai to Jest. Did it start yet? I could definitely give a hand.

**Comment by gaurav5430** [comment]
What are the updates here?

I can see that 2.x-beta is being worked on, but are there any plans to remove UNSAFE methods or to move to hooks ?

**Comment by simonhessner** [comment]
When installing `"recharts": "^2.0.0"`  using npm I get this:

> No matching version found for recharts@^2.0.0.

How can I install and test version 2.0? And where do I get the types from? I think the newest types in the @types package are for version 1.8.10.

**Comment by mkaraula** [comment]
> When installing `"recharts": "^2.0.0"` using npm I get this:
> 
> > No matching version found for recharts@^2.0.0.
> 
> How can I install and test version 2.0? And where do I get the types from? I think the newest types in the @types package are for version 1.8.10.

`npm i recharts@2.0.0-beta.6`

There is no need for `@types` because v2 is providing types.

**Comment by simonhessner** [comment]
Thanks. It works.

Referring to your last comment in this thread, did you find a solution how to set a label for the axis? VSCode complains that there is no "label" prop for XAxis and YAxis. In 1.8.5 that worked, so how to define axis labels in 2.0?

**Comment by simonhessner** [comment]
Fixed it: https://github.com/recharts/recharts/pull/2151

**Comment by kolesnikdiana** [comment]
Hey, I used **v1.8.5** but realized that there are no time scale support of Date type.
I've found an example in Demo with the [working solution](https://github.com/recharts/recharts/blob/41f363a3ec2a5d16477e4c96fe9e2153ede6be84/demo/component/ComposedChart.js) and then updated my project to use **v2.0.0-beta.6**.
But here is another problem now: as far as I use typescript I need to specify props types of custom rendered components. But there are no specific types exported. I'm wonder is it planed to support specific render type (like `ContentRenderer`) in v2.0 release?

Also I'd be happy to know:
- Are there actually breaking changes in V2 or just a refactor to use typescript?
- how stable the current v2 beta.6 version seems?
- any idea on ETA date?

Thanks

**Comment by Gunner17** [comment]
A version change sounds exciting to Recharts fans like us, but would be really great if you guys could create a link with some highlighted details that what exactly the v2.0 is going to bring in? 

Is it one of the followings:
1. typescript support and/or
2. new features/enhancements planned and/or
3. bug fixes which was difficult with 1.x.x?

Thanks in advance.

**Comment by dartess** [comment]
+1 to the comment above

and what about the release? or is the current status still beta, and it's too early to talk about a release?

**Comment by avindra** [comment]
2.x is out. There are several things left to be documented. Some of those can be located using the `docs needed` tag in the issue tracker:

https://github.com/recharts/recharts/issues?q=is%3Aissue+label%3A%22docs+needed%22

Barring a proper set of release notes, here are some of my comments on 2.x regarding some of the issues in the thread:


## Stability

@oneillsp96 Regarding stability: please send any bug reports! But I have been using 2.x beta on a fairly large project that used recharts since a long time. Personally I found 2.x to be more robust the 1.x series, and things were largely compatible even during all of the beta releases.

## Module

All default exports across the library have been purged and replaced with named exports according to the latest eslint and prettier default settings. Users who import directly from recharts source modules may need to add brackets around imports. See #2391 for an example.

### Types

@kolesnikdiana  Types (i.e., for TypeScript users) have been exported at the top level. There was a small kerfuffle with the release for Babel users, but `2.0.3` and later should be fine.

## Testing

@nvh95 Jest work in progress at #2380. Help with porting any of the tests is welcome. @sorenhoyer React 17 is supported. There is a problem in the unit tests with Enzyme blocking migration. Related to unit testing, I am exploring using the vanilla react testing utils in cases where enzyme is being used.

## Bundle size

The bundle size is [ever so slightly smaller](https://bundlephobia.com/result?p=recharts@2.0.3). It's slight in the sense that it makes no practical difference to your app. If you want to help us tackle this issue, see:

 * https://github.com/recharts/react-smooth/issues/34 (good issue detail, low-hanging fruit)
 * https://github.com/recharts/recharts/issues/2174

### Tree-shaking improved for webpack < 5 users

We also manged to get in a change to mark the package with `sideEffects:"false",` so especially Webpack users should test to see if the tree-shaker is able to prune anything to make your application bundles smaller.

**Comment by thesiti92** [comment]
is it possible to emit the typescript types adjacent to the es6 output? this would allow for imports like `import { ResponsiveContainer } from 'recharts/es6/component/ResponsiveContainer'` to ensure tree shaking. Right now, you get a typescript "no module named x" error when you try this. If we're sure that labeling the package with sideEffects: false ensures treeshaking even through a barreled import then thats awesome too!

**Comment by roger-tbg** [comment]
Anyone know how to import ContentRenderer correctly?

i.e.
```
import {
	ContentRenderer,
	Label,
	Legend,
	LegendProps,
	Line,
	LineChart,
	ResponsiveContainer,
	Tooltip,
	XAxis,
	YAxis,
} from 'recharts'
```

It tells me `TS2305: Module "recharts" has no exported member ContentRenderer`

**Comment by ckifer** [comment]
@roger-tbg I don't think that component exists (or at least I've never heard of it or reference to it)?

**Comment by roger-tbg** [comment]
> @roger-tbg I don't think that component exists (or at least I've never heard of it or reference to it)?

What i'm trying to sort out is this:
```
<Legend
	content={renderLegend}
	iconSize={0}
	align="right"
	verticalAlign="top"
	offset={-5}
/>
```

What is the TYPING of the renderLegend function:
```
const renderLegend: ContentRenderer<LegendProps> = (props: LegendProps) => {
	const { payload } = props

	return (
		<ul className="mb-4 ml-12 flex justify-between text-xs">
			{payload!.map((entry, index) => {
				return (
					<li key={`item-${index}`} className={`text-[${entry.color}]`}>
						{entry.value}
					</li>
				)
			})}
		</ul>
	)
}
```

**Comment by ckifer** [comment]
@roger-tbg could you create a new issue? This issue is closed and unrelated to what you're experiencing
